/**
 * 作品数据：按「栏目」分类，方便一个一个往里塞视频。
 * 简介统一突出能力：能…也能…并落地…
 */
const CATEGORIES = [
  "险种小课堂",
  "理赔案例",
  "大灾天气",
  "交通安全动画",
  "节假日节气祝福",
  "AI短剧",
  "怎么用AI",
  "世界杯活动",
  "社群运营",
  "活动运营",
  "新媒体运营",
  "行业观察",
  "品牌策划",
  "AI视觉",
  "个人纪实",
];

/** 筛选分组：众安栏目 vs 个人作品 */
const CATEGORY_GROUPS = {
  众安车险: [
    "险种小课堂",
    "理赔案例",
    "大灾天气",
    "交通安全动画",
    "节假日节气祝福",
    "AI短剧",
    "怎么用AI",
    "世界杯活动",
  ],
  个人作品: ["社群运营", "活动运营", "新媒体运营", "行业观察", "品牌策划", "AI视觉", "个人纪实"],
};

const WORKS = [
{
    id: "classroom-01",
    category: "险种小课堂",
    title: "险种小课堂 · 车险种类科普",
    platform: "视频号 / 小红书",
    role: "险种拆解 / 选题策划 / 图文与脚本",
    video: "videos/险种小课堂/车险小课堂.mp4",
    cover: "covers/classroom-01.png",
    desc: "能把交强险到自燃险等 7 类车险拆成车主听得懂的场景，也能独立完成从选题到图文/短视频脚本的全案。",
    highlight: "独立创作 7 险种全攻略 · 卡片式信息结构 · 熟悉购险决策痛点与合规表述 · 成片可播",
    method: "险种知识拆解 → 用户痛点对照 → 图文/短视频脚本 → 合规检查",
    outputs: "车险种类全攻略图文（7 险种）；《车险小课堂》成片",
    resumeLine: "独立完成车险种类科普全案：覆盖交强险、三者险、车损险等 7 个险种的选题、结构、脚本与成片。",
    year: "2026",
    stats: [
      { label: "能力", value: "拆解→成片" },
      { label: "险种", value: "7 类" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "claim-01",
    category: "理赔案例",
    title: "理赔案例 · 上海淹水",
    platform: "视频号",
    role: "场景策划 / 多风格脚本 / AI 分镜",
    video: "videos/理赔案例/上海淹水理赔案例.mp4",
    cover: "covers/claim-01.png",
    desc: "能把快赔服务写成女车主、24 小时理赔等可传播场景，也能输出皮克斯风与快剪风多版本脚本供 AI 直接生成。",
    highlight: "服务卖点场景化 · 同题多风格脚本 · 适配动画/广告两种生成路径 · 上海淹水成片可播",
    method: "理赔场景选题 → 多版本脚本（动画风/快剪风）→ AI 视频生成",
    outputs: "理赔案例 AI 视频脚本（多版本）；《上海淹水理赔案例》成片",
    resumeLine: "策划快赔宣传并撰写多风格脚本，覆盖女车主理赔与 24 小时快速理赔主题，并交付上海淹水理赔成片。",
    year: "2026",
    stats: [
      { label: "能力", value: "场景→成片" },
      { label: "主题", value: "上海淹水" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "weather-01",
    category: "大灾天气",
    title: "大灾天气 · 雷电预警",
    platform: "视频号",
    role: "模板设计 / 脚本 / 视频 SOP",
    video: "videos/大灾天气/雷电天气.mov",
    cover: "covers/weather-01.png",
    desc: "能设计「AI 主播 + 画中画」预警模板，也能把台风、暴雨、雷电、高温沉淀成可复用的标准化视频 SOP。",
    highlight: "固定机位主播模板 · 场景动画画中画 · 雷电成片可播 · 可延展节气祝福",
    method: "机位与话术模板 → 天气类型指令词 → 剪映合成 SOP → 多场景复用",
    outputs: "天气预警视频模板与 SOP；《雷电天气》成片",
    resumeLine: "制定 AI 天气预警视频工作流（主播+画中画），实现多天气类型模板化复用，并交付雷电预警成片。",
    year: "2026",
    stats: [
      { label: "能力", value: "模板→成片" },
      { label: "主题", value: "雷电预警" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "traffic-01",
    category: "交通安全动画",
    title: "交通安全动画 · 六一安全出行",
    platform: "视频号",
    role: "安全选题 / 动画脚本 / 分镜",
    video: "videos/儿童安全出行/六一安全出行.mov",
    cover: "covers/traffic-01.jpg",
    desc: "能做出行安全与交通规则选题，也能写成适合动画表达的教育脚本，连接车主场景与亲子安全内容。",
    highlight: "六一节点安全教育 · 儿童向动画表达 · 成片可播",
    method: "安全选题 → 动画分镜脚本 → AI/动画生成 → 审核发布",
    outputs: "《六一安全出行》动画成片",
    resumeLine: "完成儿童向出行安全动画《六一安全出行》：从选题、脚本到 AI 成片交付。",
    year: "2026",
    stats: [
      { label: "能力", value: "选题→成片" },
      { label: "主题", value: "六一出行" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "festival-01",
    category: "节假日节气祝福",
    title: "小暑 · 桑拿天上线祝福片",
    platform: "视频号",
    role: "节气选题 / 脚本 / AI 成片",
    video: "videos/24节气节日/小暑.mp4",
    cover: "covers/festival-01.png",
    desc: "能按节气节点做高温出行关怀选题，也能把预警场景写成可传播祝福片，并落地 AI 成片。",
    highlight: "小暑节点卡位 · 高温预警场景化 ·「桑拿天正式上线」钩子 · 成片可播",
    method: "节气年历排期 → 高温关怀卖点 → 脚本与主视觉 → AI 成片",
    outputs: "《小暑至，盛夏始，桑拿天正式上线》成片与封面",
    resumeLine: "完成二十四节气小暑祝福短视频：高温预警场景化表达，并交付可播成片。",
    year: "2026",
    stats: [
      { label: "能力", value: "节点→成片" },
      { label: "节气", value: "小暑" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "aidrama-01",
    category: "AI短剧",
    title: "《退婚当天，我承包了整座山》· 第一集",
    platform: "红果向 / AI 短剧",
    role: "趋势洞察 / 选题编剧 / 分镜指令 / 成片",
    video: "videos/ai-drama/ep01.mp4",
    cover: "covers/aidrama-01.png",
    desc: "能做行业洞察与选题，也能写爆款结构剧本，并落地即梦分镜指令与第一集成片。",
    highlight: "DataEye 趋势复盘 · 种田逆袭赛道卡位 · 开篇 3 秒冲突 + 付费钩子 · 人设/分镜/指令词一体",
    method: "榜单题材洞察 → 世界观与爽点地图 → 分集剧本（对白≤20字）→ 即梦分镜/场景指令 → 成片精剪",
    outputs: "趋势笔记、选题指令框架、80 集级大纲与详细剧本、第 1 集即梦指令词、第一集成片",
    resumeLine: "基于 DataEye 趋势完成种田逆袭向 AI 短剧《退婚当天，我承包了整座山》全案：从洞察、编剧到即梦分镜指令与第一集成片交付。",
    year: "2026",
    stats: [
      { label: "能力", value: "洞察→成片" },
      { label: "赛道", value: "种田/逆袭" },
      { label: "状态", value: "第1集可播" },
    ],
  },
{
    id: "howtoai-kid",
    category: "怎么用AI",
    title: "车小圈讲 AI · 合集",
    platform: "B站 / 儿童短视频",
    role: "IP 企划 / 分龄脚本 / 知识点教研",
    cover: "covers/howtoai-kid.jpg",
    video: "videos/车小圈AI魔法课/车小圈讲AI第二集.mov",
    episodes: [
      {
        title: "第二集",
        video: "videos/车小圈AI魔法课/车小圈讲AI第二集.mov",
        cover: "covers/howtoai-kid-02.png",
      },
      {
        title: "第三集",
        video: "videos/车小圈AI魔法课/车小圈讲AI第三集.mov",
        cover: "covers/howtoai-kid-03.png",
      },
    ],
    desc: "能独立策划儿童向 AI 科普 IP，也能做成可连载的分集成片，把抽象概念讲给 6–12 岁听懂。",
    highlight: "车小圈讲 AI 系列合集 · 分龄科普表达 · 第 2 / 3 集可播",
    method: "IP 企划 → 知识点选题 → 分龄脚本 → AI 动画生成 → 系列连载",
    outputs: "《车小圈讲 AI》第二集、第三集成片",
    resumeLine: "独立策划「车小圈讲 AI」儿童科普合集，完成第 2 / 3 集从脚本到 AI 成片交付。",
    year: "2026",
    stats: [
      { label: "能力", value: "合集→成片" },
      { label: "集数", value: "2 集" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "worldcup-01",
    category: "世界杯活动",
    title: "世界杯活动 · 足球小将众安",
    platform: "视频号 / 小程序",
    role: "节点策划 / 活动视频 / 物料联动",
    video: "videos/众安世界杯/足球小将众安.mp4",
    cover: "covers/worldcup-01.png",
    desc: "能借势世界杯等大事件做活动视频策划，也能联动小程序宣传物料，把内容接到曝光与转化目标上。",
    highlight: "大事件借势选题 · AI 动画成片 · 视频与小程序双端物料",
    method: "活动节点排期 → 视频脚本/成片 → 小程序宣传素材 → 复盘",
    outputs: "《足球小将众安》活动成片（已压缩网页版）",
    resumeLine: "完成世界杯节点活动视频《足球小将众安》策划与成片交付，服务曝光与转化联动。",
    year: "2026",
    stats: [
      { label: "能力", value: "节点→成片" },
      { label: "主题", value: "足球小将" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "guanxia-01",
    category: "品牌策划",
    group: "个人作品",
    title: "观夏 ·「昆仑煮雪」品牌策划案",
    platform: "课程策划 / 品牌营销全案",
    role: "STP·SWOT / 战略提案 / PPT 共创",
    video: "",
    cover: "assets/guanxia/cover.jpg",
    gallery: [
      "assets/guanxia/kunlun-product.jpg",
      "assets/guanxia/01-cover.jpg",
      "assets/guanxia/02-toc.jpg",
      "assets/guanxia/03-brand.jpg",
      "assets/guanxia/04-product.jpg",
      "assets/guanxia/05-strategy.jpg",
      "assets/guanxia/06-insight.jpg",
      "assets/guanxia/07-creative.jpg",
      "assets/guanxia/08-event.jpg",
    ],
    desc: "能把高端香氛品牌拆成 STP / SWOT 与竞品位势，也能把「昆仑煮雪」的冷暖气味转译成 TVC、共创展与社交温度场的破圈战役。",
    highlight:
      "东方植物调定位 · WO 三大战略升级 · 以昆仑煮雪打造冬日情感名片 · 从分析到活动创意闭环",
    method:
      "品牌与市场分析 → STP / SWOT → WO 战略优化 → 创意洞察（冷后藏暖）→ TVC / 共创展 / 社交传播",
    outputs:
      "最终版策划 PPT 精选页预览；产品规划；战略优化；营销洞察与创意活动方案",
    resumeLine:
      "参与观夏品牌策划案：完成市场与竞品分析、WO 战略提案，并以「昆仑煮雪」为核心设计冬日破圈营销战役。",
    year: "2025",
    stats: [
      { label: "能力", value: "分析→战役" },
      { label: "单品", value: "昆仑煮雪" },
      { label: "产出", value: "全案 PPT" },
    ],
  },
  {
    id: "oder-01",
    category: "AI视觉",
    group: "个人作品",
    title: "ODER STUDIO · 夏日模特 Campaign",
    platform: "Lovart · 时尚视觉系列",
    role: "视觉方向 / 模特设定 / Prompt 与出图筛选",
    video: "",
    cover: "covers/oder-01.jpg",
    gallery: [
      "assets/oder/campaign-01.jpg",
      "assets/oder/campaign-02.jpg",
      "assets/oder/campaign-03.jpg",
      "assets/oder/campaign-04.jpg",
      "assets/oder/campaign-05.jpg",
      "assets/oder/campaign-06.jpg",
      "assets/oder/campaign-07.jpg",
      "assets/oder/campaign-08.jpg",
      "assets/oder/campaign-09.jpg",
      "assets/oder/campaign-10.jpg",
      "assets/oder/campaign-11.jpg",
      "assets/oder/campaign-12.jpg",
    ],
    desc: "能搭北欧感模特设定与系列调性，也能用 Lovart 批量出街拍 / 夜闪 / 海滩场景，并筛成可投放的 Campaign 成组视觉。",
    highlight:
      "角色一致性可控 · 硬光胶片颗粒 · 薄荷绿统一色 · 斑马线 / 咖啡馆 / 夜闪街拍成组",
    method:
      "品牌美学基调 → 模特设定卡 → 分场景 Prompt → Lovart 出图 → 感知哈希去重与精选",
    outputs:
      "ODER STUDIO 夏日 Campaign 精选 12 张（已去重）；封面主视觉",
    resumeLine:
      "用 Lovart 完成 ODER STUDIO 夏日模特 Campaign：统一人设与色调，交付街拍与夜闪成组视觉。",
    year: "2026",
    stats: [
      { label: "能力", value: "设定→成组" },
      { label: "工具", value: "Lovart" },
      { label: "精选", value: "12 张" },
    ],
  },
{
    id: "fengkou-01",
    category: "个人纪实",
    group: "个人作品",
    title: "《风口与路口》· 关于机遇的代际对话",
    platform: "纪实短片 / AI 空镜混剪",
    role: "选题收焦 / 旁白脚本 / AI 成片",
    video: "videos/personal/fengkou.mp4",
    cover: "covers/fengkou-01.png",
    desc: "能把宽泛选题收成单一矛盾焦点，也能写旁白脚本并落地 AI 空镜混剪成片。",
    highlight: "老师反馈后收窄主线 · 三代机遇叙事 · 旁白+空镜+网络素材混剪 · 配音指令齐全",
    method: "焦点收窄 → 旁白脚本 → 7 分钟结构表 → AI 空镜/混剪 → 配音合成",
    outputs: "拍摄策划修改方案、完整旁白脚本、7 分钟混剪初稿、配音指令词、成片可播",
    resumeLine: "完成纪实短片《风口与路口》：从选题收焦、旁白脚本到 AI 空镜混剪成片全链路交付。",
    year: "2026",
    stats: [
      { label: "能力", value: "收焦→成片" },
      { label: "议题", value: "机遇/代际" },
      { label: "状态", value: "可播" },
    ],
  },
{
    id: "community-01",
    category: "社群运营",
    group: "个人作品",
    title: "今天你也不想上班吗 · 社群内容产品化",
    platform: "Conste 星社 · 社群",
    role: "Digest 体系 / 主题排期 / 成员连接 / 视觉产出",
    video: "",
    cover: "covers/community-01.png",
    gallery: [
      "assets/community/digest-onepager.png",
      "assets/community/digest-system.png",
      "assets/community/resource-map.png",
    ],
    desc: "能把日更群聊提炼成可传播 Digest，也能搭成员资源地图与主题排期，把社群从闲聊做成内容与连接产品。",
    highlight:
      "Digest 一页版四色块 · 日/周/月双层体系 · AI/金融/垂类跨行连接地图",
    method:
      "群聊采集 → Prompt 提炼 → 一页版传播 + 详细版归档 → 主题排期与跨行连接",
    outputs:
      "Digest 一页版样例；内容体系图；跨行连接地图（脱敏展示）",
    resumeLine:
      "运营「今天你也不想上班吗」：搭建 Digest 日周月体系，把群聊沉淀为选题池、项目池与连接池，并产出可传播一页版。",
    year: "2026",
    stats: [
      { label: "能力", value: "群聊→产品" },
      { label: "样例", value: "482→1 页" },
      { label: "体系", value: "日/周/月" },
    ],
  },
{
    id: "openmic-01",
    category: "活动运营",
    group: "个人作品",
    title: "阿里云 × AI 投资开放麦 · 现场运营落地",
    platform: "阿里云 · 熵简科技 · Mindex",
    role: "场务统筹 / 海报与现场物料 / 人员对接（含阿里云权益物料）",
    video: "",
    cover: "covers/openmic-01.jpg",
    gallery: [
      "assets/mindex/ai-openmic-poster.jpg",
      "assets/mindex/board-ops.png",
    ],
    desc: "能对接阿里云等联合赞助方把行业活动落地，也能独立完成海报与现场物料，并串起签到、嘉宾接待与抽奖不断档。",
    highlight:
      "阿里云联合赞助背书 · 嘉宾含阿里云 AI 生态架构师 · Qoder/礼品现场对接 · 场务+海报物料+人员对接闭环",
    method:
      "联合方物料对齐 → 布场拍照确认 → 整合报名签到 → 开场动线与贵宾接待 → 茶歇抽奖协作（含阿里云权益）→ 撤场还原",
    outputs:
      "活动海报；场务/签到执行 checklist；阿里云相关现场物料与抽奖协作落地（约 40+ 人场次）",
    resumeLine:
      "参与阿里云联合赞助「AI 投资开放麦」：负责场务、海报与现场物料及人员对接，完成布场确认、签到与权益抽奖协作。",
    year: "2026",
    stats: [
      { label: "背书", value: "阿里云" },
      { label: "规模", value: "40+ 人" },
      { label: "职责", value: "场务/物料" },
    ],
  },
{
    id: "aliyun-mdf-01",
    category: "活动运营",
    group: "个人作品",
    title: "阿里云金融 MDF 渠道招募会 · 活动策划",
    platform: "阿里云 · Mindex · 东旺智能",
    role: "活动策划 / 流程与预算 / 邀约分层设计",
    video: "",
    cover: "covers/aliyun-mdf-01.jpg",
    gallery: [
      "assets/mindex/mdf-01.jpg",
      "assets/mindex/mdf-02.jpg",
      "assets/mindex/board-mdf.png",
      "assets/mindex/mdf-03.jpg",
    ],
    desc: "能把阿里云金融 MDF 政策写成渠道伙伴听得懂的半天议程，也能设计邀约分层、预算框架与意向签约转化。",
    highlight:
      "阿里云 MDF 标题背书 ·「云聚金融·渠道共赢」· 五环节议程 · P0–P3 邀约 · 意向签约设计 · 预算 ≤10 万",
    method:
      "主题诠释 → 阿里云宣讲/政策/案例结构 → 行业背书环节 → Mindex 转化与签约 → 物料与预算清单",
    outputs:
      "《阿里云金融 MDF 渠道招募活动策划方案》；议程/物料/邀约分层与预算框架",
    resumeLine:
      "参与阿里云金融 MDF 渠道招募会策划：完成主题、五环节议程、预算与 ISV/SI 邀约分层设计。",
    year: "2026",
    stats: [
      { label: "背书", value: "阿里云" },
      { label: "主题", value: "金融 MDF" },
      { label: "产出", value: "全案策划" },
    ],
  },
  {
    id: "xhs-ip-01",
    category: "新媒体运营",
    group: "个人作品",
    title: "小红书 IP · 灵均Kikky",
    platform: "小红书",
    role: "编导 & 商务助理",
    video: "",
    cover: "assets/xhs/xhs-ip-cover.jpg",
    gallery: ["assets/xhs/xhs-ip-cover.jpg"],
    desc: "能拆竞品打出个人 IP 内容模型，也能用数据复盘做出爆款，并协助博主完成商单脚本与公转私变现闭环。",
    highlight:
      "2026.04–07 · 粉丝 1.3万 · 赞藏 33.2万 · 10+ 条 3w+ 爆款 · 30+ 品牌合作 · 变现 1w+ · 橱窗 300+ · 私域转化约 60%",
    method:
      "垂类定位与竞品拆解 → SEO/AEO 优化 → 完播/转化漏斗复盘沉淀方法论 → Brief 拆解与商单脚本 → 多形态变现与私域承接",
    outputs:
      "账号主页运营呈现；内容策划与爆款方法论；商单脚本与商务跟进；广告/探店/橱窗/咨询转化闭环",
    resumeLine:
      "担任小红书 IP「灵均Kikky」编导与商务助理（2026.04–07）：粉丝 1.3万、赞藏 33.2万，产出爆款并完成商单转化闭环。",
    year: "2026",
    stats: [
      { label: "粉丝", value: "1.3万" },
      { label: "赞藏", value: "33.2万" },
      { label: "商务", value: "30+ 品牌" },
    ],
  },
{
    id: "aidrama-insight-01",
    category: "行业观察",
    group: "个人作品",
    title: "保底退坡 · AI 漫剧回归「剧本牌桌」",
    platform: "行业观察长文 / 信息图",
    role: "选题判断 / 行业梳理 / 时间线视觉",
    video: "",
    cover: "covers/aidrama-insight-01.png",
    gallery: [
      "assets/mindex/ai-drama-timeline.jpg",
      "assets/mindex/board-drama-judgments.png",
    ],
    desc: "能把平台保底、流量与 IP 政策读成可判断的行业叙事，也能用时间线把「抢量→控质」讲清楚。",
    highlight:
      "28 天登顶到下架样本 · 保底/流量/IP 三维重估 · 平台清场反失控 · 热点时间线信息图",
    method:
      "热点事件追踪 → 平台政策对照表 → 提炼可带走判断 → 长文结构 + 时间线视觉",
    outputs:
      "《保底退坡，AI漫剧回归「剧本牌桌」》；《AI漫剧行业热点时间线》信息图",
    resumeLine:
      "撰写 AI 漫剧行业观察：梳理保底退坡与治理逻辑，并输出热点时间线视觉，服务内容判断与选题。",
    year: "2026",
    stats: [
      { label: "能力", value: "事件→判断" },
      { label: "产出", value: "文+图" },
      { label: "主线", value: "抢量→控质" },
    ],
  }
];
